
## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [ ]:
!pip install tensorflow-gpu==1.13.1

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

### Variables and constants in TF 1.x

#### Variables

In [ ]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

In [ ]:
variable

In [ ]:
#Getting shape of the variable
variable.get_shape()

In [ ]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

In [ ]:
#If a session is not initialized we cannot access values in the Variable/Tensor
variable.eval()

In [ ]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

#### Getting values from variables

In [ ]:
#Initialize session
session = tf.Session()

In [ ]:
#Initialize ALL variables for the session
session.run(tf.global_variables_initializer())

In [ ]:
#Run the eval method on the evironment with provided session to retrive values from it
variable.eval(session)

#### Constants/Tensors

In [ ]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor

In [ ]:
#We are still not able to get the real value without defining a session
tensor.eval()

#### Getting values from constants

In [ ]:
session = tf.Session()

In [ ]:
session.run(tf.global_variables_initializer())

In [ ]:
#Fatching the tensor from the tensor graph/session
tensor_value = session.run(tensor)

In [ ]:
tensor_value

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [ ]:
!pip install tensorflow-gpu==2.0.0-alpha0

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.1.0'

### Constants/Tensors

In [3]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [5]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

In [26]:
tensor_201 = tf.cast(tensor_20, dtype = tf.float64)

In [27]:
tensor_201

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[23.,  4.],
       [32., 51.]])>

### Getting values from constants

In [6]:
#Getting values straight from a TensorFlow constant to numpy - withut sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [7]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [8]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [11]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

#### Addition between scalar and tensor

In [12]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

#### Multiplication between scalar and tensor

In [13]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

#### Using Numpy functions on TensorFlow tensors

In [14]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [15]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [16]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]])

### Operations with variables

In [17]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [18]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [19]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [20]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [21]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [22]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [23]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119])>

### Storing arrays of strings

In [24]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [25]:
#How to iterate through the TF string array
for string in tf_string_array:
    print(string);

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Ragged Tensors

In [29]:
ragged = tf.ragged.constant([[1, 2], [], [1, 2, 3], [5]])

In [30]:
ragged

<tf.RaggedTensor [[1, 2], [], [1, 2, 3], [5]]>

In [34]:
ragged_numpy = np.array([[1, 2], [], [1, 2, 3], [5]])
ragged_numpy1 = np.array([[1, 2], [4, 5], [1, 2], [5, 6]])
print(ragged_numpy)
print(ragged_numpy1)

[list([1, 2]) list([]) list([1, 2, 3]) list([5])]
[[1 2]
 [4 5]
 [1 2]
 [5 6]]


### Random Values

In [15]:
random_normal = tf.random.normal((3, 2), mean=50)
random_normal

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[49.061428, 49.52026 ],
       [51.849834, 49.117874],
       [49.085712, 49.96984 ]], dtype=float32)>

In [36]:
random_uniform = tf.random.uniform((3, 2), minval=0, maxval=50, dtype=tf.int32)
random_uniform

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[17, 27],
       [ 4, 38],
       [22, 28]])>

In [23]:
tf.random.set_seed(0)
tf.random.uniform((3, 2), minval=0, maxval=50, dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[23, 29],
       [21, 17],
       [47, 24]])>

### Checkpoint

In [38]:
v1 = tf.Variable([[1, 2], [3, 4]])
v1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [40]:
checkpoint = tf.train.Checkpoint(var = v1)
save_path = checkpoint.save("./myvariable")

In [41]:
v1.assign([[0, 0], [0, 0]])
v1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [42]:
checkpoint.restore(save_path)

In [44]:
v1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>